# Семинар 1

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int64')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [7]:
vec.shape

(3, 2)

Число осей:

In [8]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [9]:
np.sum(vec)

21

In [10]:
np.sum(vec, axis=0)

array([ 9, 12])

In [11]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [12]:
vec.sum()

21

Транспонируем массив:

In [13]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [14]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [15]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [16]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [19]:
vec[:, 1]

array([2, 4, 6])

In [20]:
vec[2, :]

array([5, 6])

In [21]:
vec[1:2, 0]

array([3])

In [22]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [23]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [25]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [27]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [29]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [30]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [31]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [32]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [33]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [34]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [35]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [36]:
vec.dot(vec ** 2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [37]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [38]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [39]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [41]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [42]:
np.random.rand(2, 3)

array([[0.32247271, 0.16674399, 0.64543569],
       [0.17840073, 0.36377529, 0.32293183]])

In [43]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [44]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [45]:
np.random.normal(2, 1, size=3)

array([2.0169049 , 1.48501648, 2.24450929])

In [46]:
np.random.randint(5, 10, size=3)

array([8, 6, 8])

Почему вообще используют `numpy`?

In [47]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [48]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 14.3 s, sys: 20.2 ms, total: 14.3 s
Wall time: 14.6 s


In [50]:
%%time
C = A @ B

CPU times: user 2.92 ms, sys: 1.98 ms, total: 4.9 ms
Wall time: 4.86 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

# Завдання 1
Розгорнемо одновимірний масив. Створимо одновимірний масив, що складається з елементів масиву vec, при цьому елементи vec будуть йти в зворотньому порядку.

In [51]:
one_dim_vec = vec.reshape(-1)[::-1]
one_dim_vec

array([6, 5, 4, 3, 2, 1])

# Завдання 2
Найдем максимальний непарний елемент в даному масиві:

In [52]:
max_odd = np.max(one_dim_vec[one_dim_vec % 2 == 1])
max_odd

5

# Завдання 3
Замінимо непарні елементи масиву на на число 42

In [53]:
one_dim_vec[one_dim_vec % 2 == 1] = 42
one_dim_vec

array([ 6, 42,  4, 42,  2, 42])

# Завдання 4
Створимо масив n непарних чисел. Для цього задамо значення n:

In [54]:
n=5

Сформуємо масив:

In [55]:
first_n_odd = np.arange(2*n-1, 0, -2)
first_n_odd

array([9, 7, 5, 3, 1])

# Завдання 5
Обрахуємо найближче і найвіддаленіше числа до даного в даному масиві чисел.
Для цього задамо масив чисел:

In [56]:
given_arr = np.array([0, 1, 2, 3, 4])

і дане число:

In [57]:
num = 1.33

Тоді пара (найближче, найвіддаленіше) має вигляд (скористаємось функціями [argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) і [argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)):

In [58]:
(np.abs(given_arr - num).argmin(), np.abs(given_arr - num).argmax())

(1, 4)

# Завдання 6
Обрахуємо первісну заданого поліному (в якості константи візьмемо число 42). Для цього задамо масив коефіцієнтів і константу:


In [59]:
coeffs = np.array([4, 6, 0, 1])
constant = 42

Для знаходження масиву коефіцієнтів первісної використаємо функцію [polyint](https://numpy.org/doc/stable/reference/generated/numpy.polyint.html)

In [60]:
antiderivative_coeffs = np.polyint(coeffs)
antiderivative_coeffs_with_const = np.append(antiderivative_coeffs, constant)
antiderivative_coeffs_with_const

array([ 1.,  2.,  0.,  1.,  0., 42.])

# Завдання 7
Користуючись пунктом 6, обрахуємо першу похідну для даного поліному в даній точці.
Задамо точку:

In [61]:
x=1

Знайдемо масив коефіцієнтів похідної, користуючись функцією [polyder](https://numpy.org/doc/stable/reference/generated/numpy.polyder.html)

In [62]:
derivative_coeffs = np.polyder(antiderivative_coeffs)
derivative_coeffs

array([4., 6., 0., 1.])

Знайдемо значення похідної  в точці x, користуючись функцією [polyval](https://numpy.org/doc/stable/reference/generated/numpy.polyval.html)

In [63]:
val = np.polyval(derivative_coeffs, x)
val

11.0

# Висновки:

В ході виконання роботи ми отримали досвід роботи з бібліотекою NumPy в Python. По-перше, навчились працювати з одновимірними масивами та виконувати з ними різноманітні операції. Поглибили знання, обчислюючи найближчі та найвіддаленіші числа до заданого у масиві числа, а також обчислили первісну та першу похідну для заданого поліному. Ці завдання дозволили нам закріпити розуміння та навички у роботі з поліноміальними функціями та їх похідними. Збагатилися досвідом у використанні різних функцій бібліотеки NumPy, таких як argmin, argmax, polyint, polyder, polyval, що допомогли нам ефективно розв'язувати задачі у масивах даних.
